---
title: "COVID-19 thrombosis analysis - descriptive statistics"
author: "Reed Sorensen"
date: "3/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##

```{r echo=FALSE, message=FALSE}
library(knitr)
library(dplyr)
library(haven)
library(data.table)
library(lubridate)
library(grid)
library(gridExtra)
library(ggplot2)
base_dir <- "/mnt/workspace/GWTG/COVID19/data/"
df_in <- readRDS(file.path(base_dir, "winter_refresh_thrombosis.RDS"))
vars <- readRDS(file.path(base_dir, "vars_thromb_analysis.RDS"))
df_codebook <- readRDS(file.path(base_dir, "df_codebook_thromb_analysis.RDS")) %>%
  filter(!is.na(X2))
df <- as_factor(df_in, only_labelled = TRUE)

df_temp <- df_codebook %>%
  filter(grepl("WEIGHT", X2))

df$age_cat <- cut(df$AGEi, breaks = c(10, seq(40, 90, by = 10), 110), right = FALSE)
df$year <- as.character(year(as_date(df$ADMDT)))
df$month <- as.character(month(as_date(df$ADMDT)))
df$month2 <- sapply(df$month, function(x) ifelse(nchar(x) == 1, paste0(0, x), x))
df$year_month <- paste0(df$year, "-", df$month2)

df_codebook$n_unique <- sapply(df_codebook$X2, function(x) {
  if (FALSE) {
    x <- df_codebook$X2[20]
  }
  if (x %in% names(df)) {
    tmp <- as.data.frame(df)[, x]
    return(length(unique(tmp)))
  } else {
    return(NA)
  }
})

df_codebook$unique_vals <- sapply(df_codebook$X2, function(x) {
  if (FALSE) {
    x <- df_codebook$X2[20]
  }
  if (x %in% names(df) & df_codebook[which(df_codebook$X2 == x), "n_unique"] < 10) {
    tmp <- as.data.frame(df)[, x]
    out <- paste(unique(tmp), collapse = "; ")
    return(out)
  } else {
    return(NA)
  }
})

df_codebook$has_yes <- grepl("= Yes", df_codebook$unique_vals)



```

##

```{r echo=FALSE, message=FALSE, results="asis"}

prep_data <- function(varname) {
  if (FALSE) {
    varname <- "MEDHISTO_01"
    # varname <- "ANTIHYPRTNSV"
    # varname <- "COVDIAG"
  }
  
  df_tmp <- df[, c("age_cat", "SEX", "year_month", varname)] %>%
    setnames(old = varname, new = "tmpvar") %>%
    as.data.frame(.) %>%
    mutate(
      yesvar = NA,
      yesvar = ifelse(grepl("Yes", tmpvar), 1, yesvar),
      yesvar = ifelse(!grepl("Yes", tmpvar), 0, yesvar),
      yesvar = ifelse(is.na(tmpvar), NA, yesvar)
    )
  
  # table(complete.cases(df_tmp[, c("age_cat", "SEX", "year_month")])) # these have complete data
  
  age_denom <- as.data.frame(table(df_tmp$age_cat)) %>% rename(group = Var1, total = Freq)
  sex_denom <- as.data.frame(table(df_tmp$SEX)) %>% mutate(group = gsub("1 = |2 = ", "", Var1), total = Freq) %>%
    filter(group %in% c("Male", "Female"))
  month_denom <- as.data.frame(table(df_tmp$year_month)) %>% rename(group = Var1, total = Freq)
  allvars_denom <- bind_rows(list(age_denom, sex_denom, month_denom))[, c("group", "total")]
  
  return(list(data=df_tmp, var=varname, allvars_denom = allvars_denom))
}

create_tables_binary <- function(dat_tmp) {
  if (FALSE) {
    # dat_tmp <- prep_data("MEDHISTO_01")
    # dat_tmp <- prep_data("ANTIHYPRTNSV")
    dat_tmp <- prep_data("DDMER")
  }
  
  df_tmp <- dat_tmp$data %>%
    mutate(
      yesvar_bak = yesvar,
      yesvar = factor(yesvar, levels = c("0", "1")) )
  
  dat_total <- table(df_tmp$yesvar)
  # zero_count <- ifelse("0" %in% names(dat_total), dat_total[["0"]], 0)
  # one_count <- ifelse("1" %in% names(dat_total), dat_total[["1"]], 0)
  # df_total <- data.frame(group = "All", no = zero_count, yes = one_count)
  df_total <- data.frame(group = "All", no = dat_total[["0"]], yes = dat_total[["1"]])
  
  dat_sex <- as.matrix(t(table(df_tmp$yesvar, df_tmp$SEX))[1:2, ])
  df_sex <- data.frame(group = c("Male", "Female"), no = unname(dat_sex[,"0"]), yes = dat_sex[,"1"] )
  
  dat_age <- as.matrix(t(table(df_tmp$yesvar, df_tmp$age_cat)))
  df_age <- data.frame(group = row.names(dat_age), no = unname(dat_age[,"0"]), yes = dat_age[,"1"] )
  
  dat_month <- t(table(df_tmp$yesvar, df_tmp$year_month))
  df_month <- data.frame(group = row.names(dat_month), no = unname(dat_month[,"0"]), yes = dat_month[,"1"] )
  
  df_table <- bind_rows(list(df_total, df_sex, df_age, df_month)) %>%
    left_join(dat_tmp$allvars_denom, by = "group") %>%
    mutate(total = ifelse(group == "All", nrow(dat_tmp$data), total)) %>%
    mutate(
      pct_nonmissing = yes / (no + yes),
      pct_nonmissing2 = format(round(pct_nonmissing * 100, digits = 1), nsmall = 1),
      pct_total = yes / total,
      pct_total2 = format(round(pct_total * 100, digits = 1), nsmall = 1) )
  
  out <- list(
    df_table = df_table,
    dat_orig = df_tmp
  )
  return(out)
  
}


create_tables_continuous <- function(dat_tmp) {
  if (FALSE) {
    # dat_tmp <- prep_data("DDMER")
    dat_tmp <- prep_data("WEIGHTADM")
  }
  
  df_tmp <- dat_tmp$data %>%
    mutate(
      yesvar_bak = yesvar,
      yesvar = factor(yesvar, levels = c("0", "1")) )
  
  if (!any(df_tmp$yesvar == 1, na.rm = TRUE)) {
    
    var_tmp <- dat_tmp$var
    
    potential_unit_vars <- sapply(1:nchar(var_tmp)+1, function(i) {
      paste0(substr(var_tmp,1,i-1), "U", substr(var_tmp, i, nchar(var_tmp)))
    })
    units_var <- potential_unit_vars[which(potential_unit_vars %in% df_codebook$X2)][1]
    
    if (units_var %in% names(df)) {
      df_tmp$unit_var <- as.factor(df[, units_var])
    } else {
      df_tmp$unit_var <-as.factor("")
    }
  }
  
  df_tmp_total <- df_tmp %>%
    group_by(unit_var) %>%
    summarize(
      tmpvar_mean = mean(tmpvar, na.rm = TRUE),
      n_nonmissing = sum(!is.na(tmpvar)),
      n_total = n() ) %>%
    filter(!is.na(unit_var)) %>%
    mutate(tmpvar_mean = signif(tmpvar_mean, 4) ) %>%
    mutate(group = "All")
  
  df_tmp_age <- df_tmp %>%
    group_by(unit_var, age_cat) %>%
    summarize(
      tmpvar_mean = mean(tmpvar, na.rm = TRUE),
      n_nonmissing = sum(!is.na(tmpvar)),
      n_total = n() ) %>%
    filter(!is.na(unit_var)) %>%
    mutate(tmpvar_mean = signif(tmpvar_mean, 4) ) %>%
    rename(group = age_cat)
  
  df_tmp_sex <- df_tmp %>%
    mutate(sex2 = gsub("1 = |2 = ", "", SEX)) %>%
    filter(sex2 %in% c("Male", "Female") ) %>%
    group_by(unit_var, sex2) %>%
    summarize(
      tmpvar_mean = mean(tmpvar, na.rm = TRUE),
      n_nonmissing = sum(!is.na(tmpvar)),
      n_total = n() ) %>%
    filter(!is.na(unit_var)) %>%
    mutate(tmpvar_mean = signif(tmpvar_mean, 4) ) %>%
    rename(group = sex2)
  
  df_tmp_month <- df_tmp %>%
    group_by(unit_var, year_month) %>%
    summarize(
      tmpvar_mean = mean(tmpvar, na.rm = TRUE),
      n_nonmissing = sum(!is.na(tmpvar)),
      n_total = n() ) %>%
    filter(!is.na(unit_var)) %>%
    mutate(tmpvar_mean = signif(tmpvar_mean, 4) ) %>%
    rename(group = year_month)
  
  df_all <- bind_rows(list(df_tmp_total, df_tmp_age, df_tmp_sex, df_tmp_month)) %>%
    arrange(unit_var)
  
  unit_vars <-unique(df_all$unit_var)
  df_all2 <- lapply(1:length(unit_vars), function(i) {
    if (FALSE) {
      i <- 1
    }
    x <- unique(df_all$unit_var)[[i]]
    x2 <- strsplit(as.character(x), split = " = ")[[1]][2]
    keep_vars <- c("group", "tmpvar_mean2", "n_nonmissing")
    df_all_tmp <- filter(df_all, unit_var == x) %>%
      mutate(tmpvar_mean2 = paste0(as.character(tmpvar_mean), " ", x2)) %>%
      select(group, meanvar = tmpvar_mean2, n_nonmissing)
      
    df_all_tmp
  })
  df_all3 <- df_all2[[1]]
  if (length(df_all2) >= 2) {
    for (i in 2:length(df_all2)) df_all3 <- left_join(df_all3, df_all2[[i]], by = "group")
  }
  
  return(df_all3)
  
}




create_plot_data_binary <- function(dat_tmp) {
  if (FALSE) {
    # dat_tmp <- prep_data("MEDHISTO_06")
    dat_tmp <- prep_data("ACEIDURHOSP")
  }
  
  df_tmp <- dat_tmp$data
  
  tmp_agesex <- as.data.frame(df_tmp) %>%
    filter(!is.na(yesvar)) %>%
    # mutate(tmpvar2 = as.numeric(tmpvar) - 1) %>%
    mutate(tmpvar2 = as.numeric(yesvar)) %>%
    group_by(SEX, age_cat) %>%
    summarize(tmpvar3 = mean(tmpvar2), .groups = "drop") %>%
    as.data.frame(.)
  tmp_agesex[, c("age_lo", "age_hi")] <- as.numeric(do.call("rbind", lapply(
    as.character(tmp_agesex$age_cat), function(x) { gsub("\\D+", "", strsplit(x, split = ",")[[1]])
  })))
  tmp_agesex$age_mid <- (tmp_agesex$age_lo + tmp_agesex$age_hi) / 2
  
  ##

  tmp_month <- as.data.frame(df_tmp) %>%
    filter(!is.na(yesvar)) %>%
    filter(!year_month %in% c("2019-12", "2020-01", "2020-02")) %>%
    mutate(
      year_month_factor = factor(year_month), 
      # yvar = ifelse(tmpvar == "1 = Yes", 1, 0)
      yvar = yesvar
    )
  
  fit_tmp <- suppressWarnings({ glm(yvar ~ year_month_factor, data = tmp_month, family = "binomial") })
  
  tmp_month2 <- tmp_month %>%
    select(year_month_factor) %>%
    filter(!duplicated(.)) %>%
    arrange(year_month_factor)
  
  preds <- predict(fit_tmp, newdata = tmp_month2, se.fit = TRUE)
  inv_logit <- function(x) exp(x) / (1 + exp(x))
  
  tmp_month3 <- tmp_month2 %>%
    mutate(
      pred_logit = preds$fit,
      pred_logit_se = preds$se.fit,
      pred = plogis(pred_logit),
      pred_lo = plogis(pred_logit - 1.96 * pred_logit_se),
      pred_hi = plogis(pred_logit + 1.96 * pred_logit_se)
    )
  
  out <- list(
    tmp_agesex = tmp_agesex,
    tmp_month3 = tmp_month3
  )
  return(out)
}


```

```{r echo=FALSE, message=FALSE}

get_plots <- function(varname) {
  if (FALSE) {
    # varname <- "MEDHISTO_06"
    varname <- "ACEIDURHOSP"
  }
  
  tbl_dat <- create_tables_binary(prep_data(varname))
  plot_dat <- create_plot_data_binary(prep_data(varname))

  p1_dat <- plot_dat$tmp_agesex
  p1 <- ggplot(data = p1_dat, aes(x = age_mid, y = tmpvar3, group = SEX, color = SEX)) +
    ylim(0, max(p1_dat$tmpvar3)) +
    theme(legend.title = element_blank()) +
    xlab("Age") + ylab("Prop. yes among non-missing") +
    theme(axis.title = element_text(size = rel(0.8)), plot.title = element_text(size = rel(0.7))) +
    geom_line() + 
    ggtitle(varname)
  # p1

  p2_dat <- plot_dat$tmp_month3 %>%
    mutate(year_month_num = as.integer(year_month_factor))
  p2 <- ggplot(data = p2_dat, aes(x = year_month_num, y = pred)) +
    xlab("Time (1 = March 2019; 9 = Nov. 2020)") + ylab("Prop. yes among non-missing") +
    geom_ribbon(fill = "darkred", alpha = 0.2, aes(ymin = pred_lo, ymax = pred_hi)) +
    geom_line() +
    theme(axis.title = element_text(size = rel(0.8)), plot.title = element_text(size = rel(0.7))) +
    coord_cartesian(xlim = c(1, max(p2_dat$year_month_num)), ylim = c(0, max(p2_dat$pred)) ) +
    ggtitle(varname)
  # p2
  
  out <- list(p1=p1, p2=p2)
  return(out)
  
}


```


```{r echo=FALSE, message=FALSE}

make_grobs_binary <- function(varname) {
  if (FALSE) {
    varname <- "MEDHISTO_04"
    # varname <- "ALTNA"
  }
  
  theme1 <- ttheme_minimal(
    base_size = 10, 
    padding = unit(c(2.5,1.5), "mm"),
    core = list(fg_params = list(cex = 0.8)),
    colhead = list(fg_params = list(cex = 0.8)),
    rowhead = list(fg_params = list(cex = 0.8))
  )
  
  df_table <- create_tables_binary(prep_data(varname))$df_table
  df_table2 <- df_table %>% select(no, yes, pct_nonmissing2, total, pct_total2)
  row.names(df_table2) <- df_table$group
  
  tbl_agesex <- df_table2 %>%
    filter(!grepl("2019|2020|2021", row.names(.)))
  tbl_time <- df_table2 %>%
    filter(grepl("2019|2020|2021", row.names(.)))
  labels_tmp <- c("No", "Yes", "% yes, non-\nmissing", "All", "% yes,\nall")
  
  tbl1 <- tableGrob(tbl_agesex, cols = labels_tmp, theme = theme1)
  tbl2 <- tableGrob(tbl_time, cols = labels_tmp, theme = theme1)
  
  plots_tmp <- get_plots(varname = varname)
  p1 <- plots_tmp$p1
  p2 <- plots_tmp$p2
  # p2
  out <- list(tbl1=tbl1, tbl2=tbl2, p1=p1, p2=p2)
  # grid.arrange(ncol = 2, nrow = 2, tbl1, tbl2, p1, p2, heights = c(6,6) )
  return(out)
}

# g <- make_grobs("MEDHISTO_02")
# grid.arrange(ncol = 2, nrow = 2, g[[1]], g[[2]], g[[3]], g[[4]], heights = c(6,6) )

# grid.arrange(tbl1)

```




```{r echo=FALSE, message=FALSE, results="asis"}
# describe_binary("MEDHISTO_01")
# `r lapply(c("MEDHISTO_04", "MEDHISTO_05", "MEDHISTO_06"), function(x) { paste0("\n", x, " -- ", df_codebook %>% filter(X2 == x) %>% .[, "X7"], "\n", describe_binary(prep_data(x)$data), "\n", plot_binary(prep_data(x)$data), ",\n\n,\n\n,\n\n") })`

# `r lapply(c("MEDHISTO_04", "MEDHISTO_05", "MEDHISTO_06"), function(x) { g <- make_grobs(x); paste0("\n", x, " -- ", df_codebook %>% filter(X2 == x) %>% .[, "X7"], "\n", make_grobs(x), ",\n\n,\n\n,\n\n") })`

# `r lapply(c("MEDHISTO_04", "MEDHISTO_05", "MEDHISTO_06"), function(x) { g <- make_grobs(x); paste0("\n", x, " -- ", df_codebook %>% filter(X2 == x) %>% .[, "X7"], "\n", grid.arrange(ncol=2, nrow=2, g[[1]], g[[2]], g[[3]], g[[4]], heights = c(6,6)), ",\n\n,\n\n,\n\n") })`

# lapply(c("MEDHISTO_04", "MEDHISTO_05", "MEDHISTO_06"), function(x) { 
#   paste0(x, " -- ", df_codebook %>% filter(X2 == x) %>% .[, "X7"])
#   describe_binary(prep_data(x)$data)
#   plot_binary(prep_data(x)$data)
# })

# par(mfrow = c(2,2))
# 



df_vars2 <- data.frame(code = sapply(vars, function(x) x[1]) ) %>%
  mutate(var_id = 1:nrow(.))

# df_codebook_yesno <- df_codebook %>%
#   filter(X5 == "YESNO.") %>%
#   left_join(df_vars2, by = c("X2" = "code")) %>%
#   mutate(var_id = ifelse(is.na(var_id), 9999, var_id)) %>%
#   arrange(var_id, X2) %>%
#   filter(!grepl("Unavailable", X7))


# df_codebook_yesvars <- df_codebook %>%
#   filter(has_yes == TRUE) %>%
#   left_join(df_vars2, by = c("X2" = "code")) %>%
#   mutate(var_id = ifelse(is.na(var_id), 9999, var_id)) %>%
#   arrange(var_id, X2)

df_codebook_includevars <- df_codebook %>%
  mutate(gte10_unique_vals = n_unique >= 10) %>%
  filter(has_yes == TRUE | gte10_unique_vals == TRUE) %>%
  left_join(df_vars2, by = c("X2" = "code")) %>%
  mutate(var_id = ifelse(is.na(var_id), 9999, var_id)) %>%
  filter(X5 != "DATETIME.") %>%
  filter(!grepl("navailable", X7)) %>%
  arrange(var_id, X2)
  # filter(label != "")

# table(df_codebook_includevars$gte10_unique_vals)
# table(df_codebook_includevars$has_yes)
# with(df_codebook_includevars, table(has_yes & gte10_unique_vals))

# for (x in c("MEDHISTO_04", "MEDHISTO_05", "DDMER")) {
# for (x in df_codebook_yesno$X2) {
# for (x in df_codebook_includevars$X2[1:4]) {
for (x in df_codebook_includevars$X2) {
# itervars <- df_codebook_includevars$X2[(nrow(df_codebook_includevars)-5):nrow(df_codebook_includevars)]
# for (x in itervars) {
# for (x in "TROPADM") {
  if (FALSE) {
    # x <- "DDMER"
    x <- "TOCZMB"
    df_tmp <- df_codebook_includevars %>% filter(X2 == x)
    tmp <- df_tmp$X7
  }
  # cat("\n\n\\newpage\n")
  cat("\n\\clearpage\n")
  # cat("\n\n\n\\newpage\n\n")
  
  # x <- gsub("\\n", " ", x)
  
  if (df_codebook_includevars %>% filter(X2 == x) %>% .[, "has_yes"]) {
    
    cat(paste0(
      x, " -- ", df_codebook %>% filter(X2 == x) %>% .[, "X7"], " -- ", 
      df_codebook %>% filter(X2 == x) %>% .[, "unique_vals"], "\n\n"
    ))
    g <- suppressWarnings({ make_grobs_binary(x) })
    grid.arrange(
      ncol=2, nrow=3, 
      g[[1]], g[[2]], 
      grid.rect(gp=gpar(col="white")), 
      grid.rect(gp=gpar(col="white")), 
      g[[3]], g[[4]], heights = c(7,0.3,7)
    )
  } else if (df_codebook_includevars %>% filter(X2 == x) %>% .[, "gte10_unique_vals"]) {
    
    cat(paste0(
      x, " -- ", df_codebook %>% filter(X2 == x) %>% .[, "X7"], "\n\n"
    ))
    tbl <- suppressWarnings({ create_tables_continuous(dat_tmp = prep_data(x)) })
    n_unitvars <- (ncol(tbl)-1) / 2
    tmp_colnames <- c("Group", paste0(c("mean", "n"), rep(1:n_unitvars, each = 2)))
    print(knitr::kable(tbl, col.names = tmp_colnames))
    
  }
}


```


