---
title: "COVID-19 thrombosis analysis"
author: "Reed Sorensen"
date: "12/5/2021"
output: 
  html_document:
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Tables by highest dosage of anti-coagulation therapy {.tabset}

```{r include=FALSE, message=FALSE}
#
# make_tables.R
#
# Reed Sorensen
# September 2021
#

library(dplyr)
library(lubridate)


output_dir <- "/mnt/workspace/GWTG/COVID19/ihme_diagnostics/thrombosis/tmp_outputs/"


url_vars <- "https://raw.githubusercontent.com/rsoren/aha_covid_input_data/main/01_variable_encoding.csv"
url_newvars <- "https://raw.githubusercontent.com/rsoren/aha_covid_input_data/main/02_create_new_variables.csv"
url_table1_vars <- "https://raw.githubusercontent.com/rsoren/aha_covid_input_data/main/table1_table2_variable_list.csv"
url_table3_vars <- "https://raw.githubusercontent.com/rsoren/aha_covid_input_data/main/table3_variable_list.csv"


df_vars <- read.csv(text = RCurl::getURL(url_vars), as.is = TRUE)
df_newvars <- read.csv(text = RCurl::getURL(url_newvars), as.is = TRUE)
df_table1_vars <- read.csv(text = RCurl::getURL(url_table1_vars), as.is = TRUE)
df_table3_vars <- read.csv(text = RCurl::getURL(url_table3_vars), as.is = TRUE)

df1 <- readRDS(file.path(output_dir, "df1.RDS")) %>% as.data.frame(.)
df2 <- readRDS(file.path(output_dir, "df2.RDS")) %>% as.data.frame(.)
df4_tmp <- readRDS(file.path(output_dir, "df4_tmp.RDS")) %>% as.data.frame(.)
df4 <- readRDS(file.path(output_dir, "df4.RDS")) %>% as.data.frame(.)





source("/mnt/workspace/GWTG/COVID19/ihme_code/thrombosis/aha_covid_anticoagulation/99_functions.R")


df_vars2 <- df_vars[, c("new_var", "type")] %>% 
  mutate(stage = "orig") %>%
  filter(!duplicated(.))

df_newvars2 <- df_newvars[, c("new_variable_name", "type")] %>%
  mutate(stage = "derived") %>%
  filter(!duplicated(.))
  
df_tmp <- df_table1_vars %>%
  left_join(df_vars2, by = c("variable_name" = "new_var")) %>%
  left_join(df_newvars2, by = c("variable_name" = "new_variable_name")) %>%
  mutate(type2 = ifelse(is.na(type.x), type.y, type.x))

library(knitr)
library(kableExtra)
library(purrr)

options(scipen = 999)

```

#### Any


```{r echo=FALSE, message=FALSE}

anticoag_table_continuous(
  dat = df4,
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_general"
)

anticoag_table_binary(
  dat = df4,
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_general",
  nonmissing_denom = FALSE
)


```


#### Before ICU

```{r echo=FALSE, message=FALSE}
anticoag_table_continuous(
  dat = df4,
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_beforeicu"
)


anticoag_table_binary(
  dat = df4,
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_beforeicu"
)



  
```

#### Before health event

```{r echo=FALSE, message=FALSE}
anticoag_table_continuous(
  dat = df4,
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_beforehe"
)


anticoag_table_binary(
  dat = df4,
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_beforehe", 
  nonmissing_denom = FALSE
)

```


#### Any (post July 2020) {.active}


```{r echo=FALSE, message=FALSE}

anticoag_table_continuous(
  dat = df4 %>% filter(admission_date >= as_date("2020-08-01")),
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_general"
)

anticoag_table_binary(
  dat = df4 %>% filter(admission_date >= as_date("2020-08-01")),
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_general",
  nonmissing_denom = FALSE
)


```


#### Before ICU (post July 2020)

```{r echo=FALSE, message=FALSE}
anticoag_table_continuous(
  dat = df4 %>% filter(admission_date >= as_date("2020-08-01")),
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_beforeicu"
)


anticoag_table_binary(
  dat = df4 %>% filter(admission_date >= as_date("2020-08-01")),
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_beforeicu"
)



  
```

#### Before health event (post July 2020)

```{r echo=FALSE, message=FALSE}
anticoag_table_continuous(
  dat = df4 %>% filter(admission_date >= as_date("2020-08-01")),
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_beforehe"
)


anticoag_table_binary(
  dat = df4 %>% filter(admission_date >= as_date("2020-08-01")),
  df_labels = df_tmp,
  type_variable = "type2",
  group_var = "highest_dose_beforehe", 
  nonmissing_denom = FALSE
)

```




### Missingness

Table 3, missingness -- Variables with "NC"
```{r echo=FALSE, message=FALSE}


df5 <- as.data.frame(cbind(
  df1, 
  data.frame(during_ami_any = df2[, "during_ami_any"], admission_date = df2[, "admission_date"]) )) %>%
  mutate(pid = paste0(FACILITY_DISPLAY_ID, "__", PATIENT_DISPLAY_ID)) %>%
  arrange(pid, admission_date)

# head(df5$pid)
# head(df4_tmp$pid)
# tail(df5$pid)
# tail(df4_tmp$pid)
df5$meets_exclusion_criteria <- df4_tmp$meets_exclusion_criteria
df5$is_earliest_admission_date <- df4_tmp$is_earliest_admission_date
df5$has_duplicate_adm_dates <- df4_tmp$has_duplicate_adm_dates
    
df6 <- df5 %>% 
  filter(!has_duplicate_adm_dates) %>%
  filter(is_earliest_admission_date) %>%
  filter(!meets_exclusion_criteria %in% 1)


df_tbl3_1 <- df_table3_vars %>% filter(!is.na(nc_level))

dat3_1 <- bind_rows(lapply(1:nrow(df_tbl3_1), function(i) {
  if (FALSE) {
    i <- 1
  }
  df_i <- df_tbl3_1[i,]
  var_tmp <- df_i[1, "variable_name"]
  label_tmp <- df_i[1, "label"]
  
  df_yes_tmp <- df6[df6[, var_tmp] %in% 1, ]
  
  df_out <- data.frame(stringsAsFactors = FALSE,
    Variable = label_tmp,
    `Original variables` = paste0(var_tmp, ", ", df_i[1, "date_var"]),
    No = sum(df6[, var_tmp] %in% 2),
    NC = sum(df6[, var_tmp] %in% df_i[1, "nc_level"]),
    Missing = sum(is.na(df6[, var_tmp])),
    Yes = sum(df6[, var_tmp] %in% 1),
    `If yes, non-missing date` =  sum(!is.na(df_yes_tmp[, df_i[, "date_var"]]))
  )
  return(df_out)
}))


df_tbl3_2 <- df_table3_vars %>% filter(!is.na(nond_level))

dat3_2 <- bind_rows(lapply(1:nrow(df_tbl3_2), function(i) {
  if (FALSE) {
    i <- 7
  }
  df_i <- df_tbl3_2[i,]
  var_tmp <- df_i[1, "variable_name"]
  label_tmp <- df_i[1, "label"]
  cat(label_tmp, "\n")
  
  df_yes_tmp <- df6[df6[, var_tmp] %in% 1, ]
  
  df_out <- data.frame(stringsAsFactors = FALSE,
    Variable = label_tmp,
    `Original variables` = paste0(var_tmp, ", ", df_i[1, "date_var"]),
    `No/ND` = sum(df6[, var_tmp] %in% df_i[1, "nond_level"]),
    Missing = sum(is.na(df6[, var_tmp])),
    Yes = sum(df6[, var_tmp] %in% 1) )
  
  # if (var_tmp == "CLNBLDTRANS") {
  if (0) {
    df_out[, "If yes, non-missing date"] <- NA
  } else {
    df_out[, "If yes, non-missing date"] =  sum(!is.na(df_yes_tmp[, df_i[, "date_var"]]))
    
  }
  return(df_out)
}))


kbl(dat3_1) %>%
  kable_classic()


```

Table 3, missingness -- Variables with "No/ND"

```{r echo=FALSE, message=FALSE}
kbl(dat3_2) %>%
  kable_classic()
```


### All variables before/after applying exclusion criteria

```{r echo=FALSE, message=FALSE}

iter_vars <- unique(df_vars$new_var)
iter_vars2 <- iter_vars[!iter_vars %in% ""]

# for (var_tmp in iter_vars2) {
for (var_tmp in c(iter_vars2, unique(df_newvars$new_variable_name))) {
  if (FALSE) {
    # var_tmp <- "during_doac"
    var_tmp <- "existing_afib"
  }
  
  if (var_tmp %in% iter_vars2) {
    try({
      
      df_tmp <- filter(df_vars, new_var == var_tmp)
      
      orig_tmp <- df_tmp[1, "orig_var"]
      # cat("\n\n\n\n", var_tmp, "\n\n")
      
      if (df_tmp[1, "type"] %in% c("Binary", "Categorical", "Unit label")) {
        cat("\n\nOriginal variable, pre-exclusion:", df_tmp[1, "orig_var"])
        print(table(df1[, orig_tmp], useNA = "always"))
        
        cat("\n\nAnalytic variable, pre-exclusion")
        print(table(df4_tmp[, var_tmp], useNA = "always"))
        
        cat("\n\nAnalytic variable, post-exclusion")
        print(table(df4[, var_tmp], useNA = "always"))
      }
      
      if (df_tmp[1, "type"] %in% c("Continuous", "Integer")) {
        cat("\n\nOriginal variable, pre-exclusion:", df_tmp[1, "orig_var"])
        hist(df1[, orig_tmp], breaks = 30, main = df_tmp[1, "orig_var"])
        
        cat("\n\nAnalytic variable, pre-exclusion")
        hist(df4_tmp[, var_tmp], breaks = 30, main = paste0(var_tmp, ", pre-exclusion"))
        
        cat("\n\nAnalytic variable, post-exclusion")
        hist(df4[, var_tmp], breaks = 30, main = paste0(var_tmp, ", post-exclusion"))
      }
      
      if (df_tmp[1, "type"] %in% c("Date")) {
        cat("\n\nOriginal variable, pre-exclusion:", df_tmp[1, "orig_var"])
        hist(df1[, orig_tmp], breaks = 30, main = df_tmp[1, "orig_var"])
        
        cat("\n\nAnalytic variable, pre-exclusion")
        hist(df4_tmp[, var_tmp], breaks = 30, main = paste0(var_tmp, ", pre-exclusion"))
        
        cat("\n\nAnalytic variable, post-exclusion")
        hist(df4[, var_tmp], breaks = 30, main = paste0(var_tmp, ", post-exclusion"))
      }
      
    })
    
  } else {
      
    try({
      
      df_tmp <- filter(df_newvars, new_variable_name == var_tmp)

      cat("\n\n\n\n", var_tmp, "\n\n")

      if (df_tmp[1, "type"] %in% c("Binary", "Categorical", "Unit label")) {
        cat("\n\nAnalytic variable, pre-exclusion")
        print(table(df4_tmp[, var_tmp], useNA = "always"))

        cat("\n\nAnalytic variable, post-exclusion")
        print(table(df4[, var_tmp], useNA = "always"))
      }

      if (df_tmp[1, "type"] %in% c("Continuous", "Integer")) {

        cat("\n\nAnalytic variable, pre-exclusion")
        hist(df4_tmp[, var_tmp], breaks = 30, main = paste0(var_tmp, ", pre-exclusion"))

        cat("\n\nAnalytic variable, post-exclusion")
        hist(df4[, var_tmp], breaks = 30, main = paste0(var_tmp, ", post-exclusion"))
      }

      if (df_tmp[1, "type"] %in% c("Date")) {

        cat("\n\nAnalytic variable, pre-exclusion")
        hist(df4_tmp[, var_tmp], breaks = 30, main = paste0(var_tmp, ", pre-exclusion"))

        cat("\n\nAnalytic variable, post-exclusion")
        hist(df4[, var_tmp], breaks = 30, main = paste0(var_tmp, ", post-exclusion"))
      }
      
    })
  }
  
}



```
